version: '3.1'

volumes: 
  mssql:

services:

  mssql:
    container_name: mssql
    image: "microsoft/mssql-server-linux:2017-CU13"
    volumes: 
      - mssql:/var/opt/mssql/data
      - ./mssql:/mssql
      - ./mssql/odbc.ini:/etc/odbc.ini
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "P@ssw0rd2020"
      ACCEPT_EULA: "Y"
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P P@ssw0rd2020 -d Master -i /mssql/checkdb.sql
      #/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P P@ssw0rd2020 -d Master -i /mssql/checkdb.sql
  
  totvslic:
    container_name: totvslic
    build: 
      ./totvslic
    volumes:
      - ./totvslic/appserver.ini:/totvs/totvslic/bin/appserver/appserver.ini
      - ./totvslic/licenseserver.ini:/totvs/totvslic/bin/appserver/licenseserver.ini
    ports: 
      - 5555:5555
      - 2234:2234
      
    
  dbaccess:
    container_name: dbaccess
    build: 
      ./dbaccess
    volumes:
      - ./dbaccess/odbc.ini:/etc/odbc.ini
      - ./dbaccess/dbaccess.ini:/totvs/dbaccess/dbaccess.ini
    ports: 
      - 7890:7890
    depends_on: 
      - mssql
      - totvslic

  protheus:
    container_name: protheus
    build: 
      ./appserver
    volumes:
      - ./appserver/appserver.ini:/totvs/protheus/bin/appserver/appserver.ini
    ports: 
      - 1234:1234
      - 8079:8079
    depends_on: 
      - dbaccess
      - totvslic
