version: '3.1'

volumes: 
  mssql:

services:

  mssql:
    container_name: mssql
    image: "microsoft/mssql-server-linux:2017-CU13"
    volumes: 
      - mssql:/var/opt/mssql/data
      - ./mssql:/mssql
      - ./mssql/odbc.ini:/etc/odbc.ini
    ports:
      - 1433:1433
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'P@ssw0rd2019' -d Master -i /mssql/checkdb.sql
    environment:
      SA_PASSWORD: "P@ssw0rd2020"
      ACCEPT_EULA: "Y"
      