version: '3.1'

volumes: 
  mssql:

services:

  mssql:
    container_name: mssql
    image: "microsoft/mssql-server-linux:2017-CU13"
    volumes: 
      - mssql:/var/opt/mssql/data
      - ./mssql:/mssql
      - ./mssql/odbc.ini:/etc/odbc.ini
    ports:
      - 1433:1433
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'P@ssw0rd2019' -d Master -i /mssql/checkdb.sql
    environment:
      SA_PASSWORD: "P@ssw0rd2020"
      ACCEPT_EULA: "Y"

  dbaccess:
    container_name: dbaccess
    build: 
      ./dbaccess
    volumes:
      - ./dbaccess/odbc.ini:/etc/odbc.ini
      - ./dbaccess/dbaccess.ini:/totvs/dbaccess/dbaccess.ini
    ports: 
      - 7890:7890
    depends_on: 
      - mssql

  protheus:
    container_name: protheus
    build: 
      ./appserver
    volumes:
      - ./appserver/appserver.ini:/totvs/protheus/bin/appserver/appserver.ini
    ports: 
      - 1234:1234
      - 8079:8079
    depends_on: 
      - dbaccess
