FROM microsoft/mssql-tools
LABEL maintainer="Marcus Sullivan from TIBrasil.net"
COPY ./dbaccess /totvs/dbaccess
COPY ./dbaccess.ini /totvs/dbaccess/dbaccess.ini
COPY ./init.sh /totvs/dbaccess/init.sh
EXPOSE 7890
USER root
WORKDIR /totvs/dbaccess
RUN /totvs/dbaccess/init.sh
ENTRYPOINT [ "/totvs/dbaccess/dbaccess64" ]
