USE [master] 
GO

drop database dadosadv
GO

USE [master];
GO
CREATE LOGIN siga 
    WITH PASSWORD    = N'msiga',
    CHECK_POLICY     = OFF,
    CHECK_EXPIRATION = OFF;
GO
EXEC sp_addsrvrolemember 
    @loginame = N'siga', 
    @rolename = N'sysadmin';
GO

CREATE DATABASE [dadosadv] ON  PRIMARY 
( NAME = N'dadosadv', FILENAME = N'/var/opt/mssql/data/dadosadv.mdf' , SIZE = 3072KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'dadosadv_log', FILENAME = N'/var/opt/mssql/data/dadosadv_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
 COLLATE Latin1_General_BIN
GO
ALTER DATABASE [dadosadv] SET COMPATIBILITY_LEVEL = 100
GO
ALTER DATABASE [dadosadv] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [dadosadv] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [dadosadv] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [dadosadv] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [dadosadv] SET ARITHABORT OFF 
GO
ALTER DATABASE [dadosadv] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [dadosadv] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [dadosadv] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [dadosadv] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [dadosadv] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [dadosadv] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [dadosadv] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [dadosadv] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [dadosadv] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [dadosadv] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [dadosadv] SET  DISABLE_BROKER 
GO
ALTER DATABASE [dadosadv] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [dadosadv] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [dadosadv] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [dadosadv] SET  READ_WRITE 
GO
ALTER DATABASE [dadosadv] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [dadosadv] SET  MULTI_USER 
GO
ALTER DATABASE [dadosadv] SET PAGE_VERIFY CHECKSUM  
GO
USE [dadosadv]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [dadosadv] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
