USE [master]
GO

CREATE LOGIN siga 
    WITH PASSWORD    = N'msiga',
    CHECK_POLICY     = OFF,
    CHECK_EXPIRATION = OFF;
GO

EXEC sp_addsrvrolemember 
    @loginame = N'siga', 
    @rolename = N'sysadmin';
GO

CREATE DATABASE [dadosadv] ON  PRIMARY 
( NAME = N'dadosadv', FILENAME = N'/var/opt/mssql/data/dadosadv.mdf' , SIZE = 3072KB , FILEGROWTH = 1024KB )
LOG ON 
( NAME = N'dadosadv_log', FILENAME = N'/var/opt/mssql/data/dadosadv_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
COLLATE Latin1_General_BIN
ALTER DATABASE [dadosadv] SET COMPATIBILITY_LEVEL = 100
ALTER DATABASE [dadosadv] SET ANSI_NULL_DEFAULT OFF 
ALTER DATABASE [dadosadv] SET ANSI_NULLS OFF 
ALTER DATABASE [dadosadv] SET ANSI_PADDING OFF 
ALTER DATABASE [dadosadv] SET ANSI_WARNINGS OFF 
ALTER DATABASE [dadosadv] SET ARITHABORT OFF 
ALTER DATABASE [dadosadv] SET AUTO_CLOSE OFF 
ALTER DATABASE [dadosadv] SET AUTO_CREATE_STATISTICS ON 
ALTER DATABASE [dadosadv] SET AUTO_SHRINK OFF 
ALTER DATABASE [dadosadv] SET AUTO_UPDATE_STATISTICS ON 
ALTER DATABASE [dadosadv] SET CURSOR_CLOSE_ON_COMMIT OFF 
ALTER DATABASE [dadosadv] SET CURSOR_DEFAULT  GLOBAL 
ALTER DATABASE [dadosadv] SET CONCAT_NULL_YIELDS_NULL OFF 
ALTER DATABASE [dadosadv] SET NUMERIC_ROUNDABORT OFF 
ALTER DATABASE [dadosadv] SET QUOTED_IDENTIFIER OFF 
ALTER DATABASE [dadosadv] SET RECURSIVE_TRIGGERS OFF 
ALTER DATABASE [dadosadv] SET  DISABLE_BROKER 
ALTER DATABASE [dadosadv] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
ALTER DATABASE [dadosadv] SET DATE_CORRELATION_OPTIMIZATION OFF 
ALTER DATABASE [dadosadv] SET PARAMETERIZATION SIMPLE 
ALTER DATABASE [dadosadv] SET  READ_WRITE 
ALTER DATABASE [dadosadv] SET RECOVERY SIMPLE 
ALTER DATABASE [dadosadv] SET  MULTI_USER 
ALTER DATABASE [dadosadv] SET PAGE_VERIFY CHECKSUM  
GO 

USE [dadosadv]
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') 
    ALTER DATABASE [dadosadv] MODIFY FILEGROUP [PRIMARY] DEFAULT

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND  TABLE_NAME = 'SX2990')
BEGIN
    USE [master]
    RESTORE DATABASE [dadosadv] FROM  DISK = '/mssql/p12127.bak' WITH  FILE = 1, NOUNLOAD,  REPLACE,  STATS = 5
END

USE [dadosadv] 
exec sp_changedbowner siga
